Parameters:
  ServerName:
    Description: ServerName to be set
    Type: String
  keyname:
    Description: Pick the key
    Type: AWS::EC2::KeyPair::KeyName 
  AMI:
    Description: AMI details 
    Type: AWS::EC2::Image::Id 
  InstanceType:
    Description: Server Type
    Type: String
  SecurityGroupsList:
    Description: SG details
    Type: String 

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref keyname
      DisableApiTermination: False
      ImageId: !Ref AMI
      SubnetId: subnet-0dd52f16b706ceda3
      InstanceType: !Ref InstanceType
      Monitoring: false
      SecurityGroupIds:
        - !Ref SecurityGroupsList
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
        touch /tmp/itworks.txt
      Tags:
        - Key: Name
          Value: !Ref ServerName
          
  ScreeningRequestDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "some-name"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "screening_result"
          AttributeType: "S"
        - AttributeName: "external_screeningid"
          AttributeType: "S"
        - AttributeName: "supplier_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "external_screeningid"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "ScreeningResultIndex"
          KeySchema:
            - AttributeName: "screening_result"
              KeyType: HASH
          Projection:
            ProjectionType: "ALL"
        - IndexName: "SupplierIdScreeningResultIndex"
          KeySchema:
            - AttributeName: "supplier_id"
              KeyType: HASH
            - AttributeName: "screening_result"
              KeyType: RANGE
          Projection:
            ProjectionType: "ALL"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  EC2InstancePrivateIPAddress:
    Description: "Private IP address of EC2 instance"
    Value: !GetAtt myEC2Instance.PrivateIp
    Export:
      Name: "EC2-instance-private-ip-v4-address"
  EC2InstanceAvailabilityZone:
    Description: "EC2 instance availability zone"
    Value: !GetAtt myEC2Instance.AvailabilityZone
    Export:
      Name: "EC2-instance-availability-zone"
  ScreeningRequestDynamoTableName:
    Description: "Screening Request Dynamo Table Name"
    Value: !Ref ScreeningRequestDynamoTable
    Export:
      Name: "screeningrequesttable-TableName" 
